# Generated by Django 2.2.4 on 2020-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0002_auto_20200205_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_P_T', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
