# Generated by Django 2.2.4 on 2020-02-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0003_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='B_M_L_T',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='highlights',
            name='C_C_H',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='highlights',
            name='D_M_L_T',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='highlights',
            name='M_M_L_T',
            field=models.CharField(default='', max_length=500),
        ),
    ]
