# Generated by Django 2.2.4 on 2020-02-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0004_auto_20200209_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlights',
            old_name='B_M_L_T',
            new_name='BMLT',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='B_P_T',
            new_name='BPT',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='C_C_H',
            new_name='CCH',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='D_M_L_T',
            new_name='DMLT',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='M_M_L_T',
            new_name='MMLT',
        ),
    ]
