# Generated by Django 2.2.4 on 2020-02-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0005_auto_20200209_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlights',
            old_name='BMLT',
            new_name='hig',
        ),
        migrations.RemoveField(
            model_name='highlights',
            name='BPT',
        ),
        migrations.RemoveField(
            model_name='highlights',
            name='CCH',
        ),
        migrations.RemoveField(
            model_name='highlights',
            name='DMLT',
        ),
        migrations.RemoveField(
            model_name='highlights',
            name='MMLT',
        ),
        migrations.AddField(
            model_name='highlights',
            name='course',
            field=models.CharField(default='', max_length=20),
        ),
    ]
