# Generated by Django 2.2.4 on 2020-02-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0006_auto_20200209_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='adm',
            field=models.CharField(default='', max_length=500, verbose_name='Admission'),
        ),
        migrations.AddField(
            model_name='highlights',
            name='eli',
            field=models.CharField(default='', max_length=500, verbose_name='eligibility'),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='hig',
            field=models.CharField(default='', max_length=500, verbose_name='highlights'),
        ),
    ]
