# Generated by Django 2.2.4 on 2020-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0007_auto_20200213_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='medicareOne/Faculty')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('post', models.CharField(default='', max_length=20, verbose_name='Post')),
                ('subject', models.CharField(default='', max_length=50, verbose_name='Subject')),
                ('degree', models.CharField(default='', max_length=50, verbose_name='Degree')),
            ],
        ),
    ]
