# Generated by Django 2.2.4 on 2020-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0008_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subject',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='', upload_to='Faculty/images'),
        ),
    ]
