# Generated by Django 2.2.4 on 2020-03-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0009_auto_20200311_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='Elite/images')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('degree', models.CharField(default='', max_length=50, verbose_name='Degree')),
                ('year', models.CharField(default='', max_length=20, verbose_name='Year')),
                ('percentage', models.CharField(default='', max_length=20, verbose_name='Percentage')),
            ],
        ),
    ]
