# Generated by Django 2.2.4 on 2020-06-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0010_elite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrasturcture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='Infrastructure/images', verbose_name='Image')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Description')),
            ],
        ),
    ]
