# Generated by Django 2.2.4 on 2020-06-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrasturcture',
            name='cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='medicareOne.Category'),
        ),
    ]
