# Generated by Django 2.2.4 on 2020-06-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0013_infrasturcture_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrasturcture',
            name='description',
            field=models.CharField(default='', max_length=50000, verbose_name='Description'),
        ),
    ]
