# Generated by Django 2.2.4 on 2020-06-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0014_auto_20200621_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='Add/img', verbose_name='Add')),
            ],
        ),
    ]
