# Generated by Django 3.0.2 on 2020-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareOne', '0015_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.AlterField(
            model_name='highlights',
            name='adm',
            field=models.CharField(default='', max_length=5000, verbose_name='Admission'),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='eli',
            field=models.CharField(default='', max_length=5000, verbose_name='eligibility'),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='hig',
            field=models.CharField(default='', max_length=5000, verbose_name='highlights'),
        ),
    ]
